name: Auto Publish Report

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish report
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '${{ secrets.RAROG_SCHEDULER_BODY }}' \
            "${{ secrets.RAROG_WEBAPP_URL }}"
